rem **************************************
rem * Color constants
rem **************************************
SHARED CONST COLOR_BLACK       = 0
SHARED CONST COLOR_WHITE       = 1
SHARED CONST COLOR_RED         = 2
SHARED CONST COLOR_CYAN        = 3
SHARED CONST COLOR_PURPLE      = 4
SHARED CONST COLOR_GREEN       = 5
SHARED CONST COLOR_BLUE        = 6
SHARED CONST COLOR_YELLOW      = 7

SHARED CONST COLOR_ORANGE      = 8
SHARED CONST COLOR_BROWN       = 9
SHARED CONST COLOR_LIGHTRED    = 10
SHARED CONST COLOR_DARKGRAY    = 11
SHARED CONST COLOR_MIDDLEGRAY  = 12
SHARED CONST COLOR_LIGHTGREEN  = 13
SHARED CONST COLOR_LIGHTBLUE   = 14
SHARED CONST COLOR_LIGHTGRAY   = 15

SHARED CONST MCOLOR_BLACK      = 8
SHARED CONST MCOLOR_WHITE      = 9
SHARED CONST MCOLOR_RED        = 10
SHARED CONST MCOLOR_CYAN       = 11
SHARED CONST MCOLOR_PURPLE     = 12
SHARED CONST MCOLOR_GREEN      = 13
SHARED CONST MCOLOR_BLUE       = 14
SHARED CONST MCOLOR_YELLOW     = 15
